/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Balance, BalanceInterface } from "../../contracts/Balance";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "adr",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Withraw",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withraw",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class Balance__factory {
  static readonly abi = _abi;
  static createInterface(): BalanceInterface {
    return new utils.Interface(_abi) as BalanceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Balance {
    return new Contract(address, _abi, signerOrProvider) as Balance;
  }
}
