/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "Balance",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Balance__factory>;
    getContractFactory(
      name: "GameContext",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GameContext__factory>;
    getContractFactory(
      name: "Referral",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Referral__factory>;
    getContractFactory(
      name: "RockPaperScissors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RockPaperScissors__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "Balance",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Balance>;
    getContractAt(
      name: "GameContext",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GameContext>;
    getContractAt(
      name: "Referral",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Referral>;
    getContractAt(
      name: "RockPaperScissors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RockPaperScissors>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
