/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Balance } from "./Balance";
export type { GameContext } from "./GameContext";
export type { Referral } from "./Referral";
export type { RockPaperScissors } from "./RockPaperScissors";
